apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: qs-rest-client-server
spec:
  workspaces:
  - name: shared-data
    subPath: sources
    persistentVolumeClaim:
      claimName: maven-cache
  - name: maven-cache
    subPath: maven-repo-cache
    persistentVolumeClaim:
      claimName: maven-cache
  - name: push-secret
    secret:
      secretName: kaniko-push-secret
  pipelineRef:
    name: wildfly-s2i-build-pipeline
  params:
    - name: gitUrl
      value: "https://github.com/wildfly/quickstart.git"
    - name: revision
      value: "26.0.0.Final"
    - name: contextDir
      value: "microprofile-rest-client"
    - name: outputImage
      value: "quay.io/jfdenise/rest-client-server-qs:latest"
    - name: ARTIFACT_DIR
      value: "country-server/target"
    - name: MAVEN_ARGS_APPEND
      value: "-am -pl country-server"
    - name: GALLEON_PROVISION_FEATURE_PACKS
      value: "org.wildfly:wildfly-galleon-pack:26.0.0.Final"
    - name: GALLEON_PROVISION_LAYERS
      value: "jaxrs-server,microprofile-platform"
