apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-task
spec:
  params:
  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
  - name: CONTEXT
  workspaces:
    - name: sources
      description: The src dir
  steps:
    - name: echo-path
      env:
      - name: MYDOCKERFILE
        value: "$(params.DOCKERFILE)"
      - name: MYCONTEXT
        value: "$(params.CONTEXT)"
        
      workingDir: $(workspaces.sources.path)
      securityContext:
        runAsUser: 0
      image: "quay.io/jfdenise/wildfly-s2i-jdk11:latest"
      script: |
        #!/usr/bin/env sh
        set -eu
        ls -l "$MYCONTEXT"
        cat "$MYDOCKERFILE"
