apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: wildfly-s2i-build-pipeline
spec:
  params:
    - name: gitUrl
    - name: revision
    - name: contextDir
    - name: outputImage
  workspaces:
    - name: shared-data
    - name: push-secret
  tasks:
    - name: git-clone-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(params.revision)"
        - name: deleteExisting
          value: "true"
        - name: depth
          value: "1"
    - name: wildfly-s2i-build
      taskRef:
        name: wildfly-s2i-build-task
      params:
        - name: contextDir
          value: "$(params.contextDir)"
      runAfter: 
        - git-clone-repo
      workspaces:
        - name: sources
          workspace: shared-data
    - name: kaniko-build-push
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: "$(params.outputImage)"
        - name: DOCKERFILE
          value: "$(tasks.wildfly-s2i-build.results.dockerFile)"
        - name: CONTEXT
          value: "$(tasks.wildfly-s2i-build.results.dockerBuildContext)"
      runAfter: 
        - wildfly-s2i-build
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: push-secret