apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: wildfly-s2i-build-pipeline-run
spec:
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: push-secret
    secret:
      secretName: kaniko-push-secret
  pipelineRef:
    name: wildfly-s2i-build-pipeline
  params:
    - name: gitUrl
      value: "http://github.com/wildfly/wildfly-s2i"
    - name: revision
      value: "v2"
    - name: contextDir
      value: "test/test-app"
    - name: outputImage
      value: "quay.io/jfdenise/sample-test-app-v2:latest"
